[application]
env = "development"
port = 1810
log-level = "h2=info,debug"

[misc]
max_query_results = 1000

[database]
pool_size = 100
port = 1234
name = "listings"
host = "localhost"
user = "postgres"
password = "password"

# vim:ft=toml

